//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Dostawa_materialu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_Dostawa_materialu()
        {
            this.DM_Sklad_dostawy_materialu = new HashSet<DM_Sklad_dostawy_materialu>();
        }
    
        public int Id_dostawy { get; set; }
        public Nullable<int> Id_pracownika { get; set; }
        public System.DateTime data_dostawy { get; set; }
        public string uwagi { get; set; }
    
        public virtual DZ_Pracownik DZ_Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Sklad_dostawy_materialu> DM_Sklad_dostawy_materialu { get; set; }
    }
}
