//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DZ_Klient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DZ_Klient()
        {
            this.DZ_Zamowienie_klienta = new HashSet<DZ_Zamowienie_klienta>();
        }
    
        public int Id_klienta { get; set; }
        public string nazwa_firmy { get; set; }
        public string nip { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string adres { get; set; }
        public string miasto { get; set; }
        public string kod_pocztowy { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string numer_rachunku { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DZ_Zamowienie_klienta> DZ_Zamowienie_klienta { get; set; }
    }
}
