//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DZ_Rachunki
    {
        public int Id_rachunki { get; set; }
        public Nullable<int> Id_rodzaj_rachunku { get; set; }
        public double koszt { get; set; }
        public System.DateTime data_zaplaty { get; set; }
    
        public virtual DZ_Rodzaj_rachunku DZ_Rodzaj_rachunku { get; set; }
    }
}
