//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Wydanie_czesci_dla_produkcji
    {
        public int Id_wydania_czesci { get; set; }
        public int Id_pracownik_pobierajacy { get; set; }
        public int Id_pracownik_wydajacy { get; set; }
        public System.DateTime Data_i_godzina_wydania { get; set; }
        public string Uwagi { get; set; }
    
        public virtual DZ_Pracownik DZ_Pracownik { get; set; }
        public virtual DZ_Pracownik DZ_Pracownik1 { get; set; }
    }
}
