//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Czynnosc_w_ramach_obslugi_serw_wew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DP_Czynnosc_w_ramach_obslugi_serw_wew()
        {
            this.DP_Serwis_wewnetrzny_obsluga = new HashSet<DP_Serwis_wewnetrzny_obsluga>();
        }
    
        public int Id_czynnosc_w_ramach_obslugi_serw_wew { get; set; }
        public Nullable<int> Id_nazwa_obslugi { get; set; }
        public Nullable<int> Id_czynnosc { get; set; }
    
        public virtual DP_Czynnosc DP_Czynnosc { get; set; }
        public virtual DP_Nazwa_obslugi DP_Nazwa_obslugi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_Serwis_wewnetrzny_obsluga> DP_Serwis_wewnetrzny_obsluga { get; set; }
    }
}
