//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM_Czesci
    {
        public int Numer_czesci { get; set; }
        public string Nazwa { get; set; }
        public int Ilosc_pocz_tkowa { get; set; }
    }
}
