//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Pracownik
    {
        public int Numer_pracownika { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string e_mail { get; set; }
        public string adres { get; set; }
        public string miasto { get; set; }
        public string Kod_pocztowy { get; set; }
        public System.DateTime Data_urodzenia { get; set; }
        public string Numer_telefonu { get; set; }
        public string Numer_rachunku { get; set; }
    }
}
