//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Wycena_sz_zamowienia
    {
        public int Identyfikator_wyceny_zamowienia { get; set; }
        public int Identyfikator_szczegolow_zamowienia_klienta { get; set; }
        public int Numer_pliku { get; set; }
        public double koszt { get; set; }
        public int Czas_wykonania { get; set; }
    }
}
