//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Czesc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_Czesc()
        {
            this.DM_Parametr_czesci = new HashSet<DM_Parametr_czesci>();
            this.DM_Sklad_dostawy_czesci = new HashSet<DM_Sklad_dostawy_czesci>();
            this.DM_Szczegoly_wydania_czesci = new HashSet<DM_Szczegoly_wydania_czesci>();
            this.DZ_Szczegoly_zam_czesci = new HashSet<DZ_Szczegoly_zam_czesci>();
        }
    
        public int Id_czesci { get; set; }
        public string Nazwa { get; set; }
        public int Id_model_maszyny { get; set; }
        public int Ilosc_poczatkowa { get; set; }
    
        public virtual DP_Model_maszyny DP_Model_maszyny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Parametr_czesci> DM_Parametr_czesci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Sklad_dostawy_czesci> DM_Sklad_dostawy_czesci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Szczegoly_wydania_czesci> DM_Szczegoly_wydania_czesci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DZ_Szczegoly_zam_czesci> DZ_Szczegoly_zam_czesci { get; set; }
    }
}
