//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_Material()
        {
            this.DM_Sklad_dostawy_materialu = new HashSet<DM_Sklad_dostawy_materialu>();
            this.DM_Szczegoly_wydania_materialu = new HashSet<DM_Szczegoly_wydania_materialu>();
            this.DM_Wlasciwosci_materialu = new HashSet<DM_Wlasciwosci_materialu>();
            this.DP_Po_material_wydruk = new HashSet<DP_Po_material_wydruk>();
            this.DZ_Szczegoly_zamowienia_klienta = new HashSet<DZ_Szczegoly_zamowienia_klienta>();
            this.DZ_Szczegoly_zam_materialu = new HashSet<DZ_Szczegoly_zam_materialu>();
        }
    
        public int Id_materialu { get; set; }
        public int Id_rodzaj_materialu { get; set; }
        public string nazwa { get; set; }
    
        public virtual DM_Rodzaj_materialu DM_Rodzaj_materialu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Sklad_dostawy_materialu> DM_Sklad_dostawy_materialu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Szczegoly_wydania_materialu> DM_Szczegoly_wydania_materialu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Wlasciwosci_materialu> DM_Wlasciwosci_materialu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_Po_material_wydruk> DP_Po_material_wydruk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DZ_Szczegoly_zamowienia_klienta> DZ_Szczegoly_zamowienia_klienta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DZ_Szczegoly_zam_materialu> DZ_Szczegoly_zam_materialu { get; set; }
    }
}
