//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Szczegoly_magazynu_gotowych_produktow
    {
        public Nullable<int> Id_magazynu_gotowych_produktow { get; set; }
        public int Id_produktu { get; set; }
        public int ilosc { get; set; }
    
        public virtual DM_Magazyn_gotowych_produktow DM_Magazyn_gotowych_produktow { get; set; }
        public virtual DP_Produkt DP_Produkt { get; set; }
    }
}
