//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Szczegoly_wydania_czesci
    {
        public int Id_wydania_czesci { get; set; }
        public int Id_czesci { get; set; }
        public int Ilosc { get; set; }
    
        public virtual DM_Czesc DM_Czesc { get; set; }
        public virtual DM_Wydanie_czesci DM_Wydanie_czesci { get; set; }
    }
}
