//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Sklad_dostawy_czesci
    {
        public int Id_dostawy { get; set; }
        public Nullable<int> Id_dostawcy { get; set; }
        public int Id_czesci { get; set; }
        public int Id_zamowienie_zewn { get; set; }
        public int ilosc { get; set; }
        public int cena_jednostkowa_czesci { get; set; }
    
        public virtual DM_Czesci DM_Czesci { get; set; }
        public virtual DM_Dostawa_czesci DM_Dostawa_czesci { get; set; }
        public virtual DM_Dostawcy DM_Dostawcy { get; set; }
        public virtual DZ_Zamowienie_zewn DZ_Zamowienie_zewn { get; set; }
    }
}
