//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Sklad_dostawy_maszyn
    {
        public int Id_dostawy { get; set; }
        public Nullable<int> Id_dostawcy { get; set; }
        public int Id_maszyn { get; set; }
        public int Id_zamowienie_zewn { get; set; }
        public int Ilosc { get; set; }
        public int Cena_jednostkowa_maszyny { get; set; }
    
        public virtual DM_Dostawa_maszyn DM_Dostawa_maszyn { get; set; }
        public virtual DM_Dostawca DM_Dostawca { get; set; }
        public virtual DP_Maszyna DP_Maszyna { get; set; }
        public virtual DZ_Zamowienie_zewn DZ_Zamowienie_zewn { get; set; }
    }
}
