//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Wlasciwosci_materialu
    {
        public int Id_materialu { get; set; }
        public int Id_wlasciwosc { get; set; }
        public string wartosc { get; set; }
    
        public virtual DM_Material DM_Material { get; set; }
        public virtual DM_Wlasciwosc DM_Wlasciwosc { get; set; }
    }
}
