//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Obsluga
    {
        public int Id_obslugi { get; set; }
        public int Id_nazwa_obslugi { get; set; }
        public int Id_rodzaj_maszyny { get; set; }
        public int Id_co_ile_obsluga { get; set; }
    
        public virtual DP_Co_ile_obsluga DP_Co_ile_obsluga { get; set; }
        public virtual DP_Nazwa_obslugi DP_Nazwa_obslugi { get; set; }
        public virtual DP_Rodzaj_maszyny DP_Rodzaj_maszyny { get; set; }
    }
}
