//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Po_maszyna_wydruk
    {
        public int Id_maszyna_wydruk { get; set; }
        public int Id_po_wydr_proces { get; set; }
        public int Id_maszyny { get; set; }
    
        public virtual DP_Maszyna DP_Maszyna { get; set; }
        public virtual DP_Po_wydr_proc DP_Po_wydr_proc { get; set; }
    }
}
