//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_prod_material
    {
        public int Id_proces_produkcyjny { get; set; }
        public int Id_materialu { get; set; }
        public double Ilosc_zuzytego_materialu { get; set; }
    
        public virtual DM_Material DM_Material { get; set; }
        public virtual DP_Proces_produkcyjny DP_Proces_produkcyjny { get; set; }
    }
}
