//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_prod_wydruk
    {
        public int Id_prod_wydruk { get; set; }
        public int Id_proces_produkcyjny { get; set; }
        public int Id_maszyny { get; set; }
        public int Czas_wydruku { get; set; }
    
        public virtual DP_Maszyna DP_Maszyna { get; set; }
        public virtual DP_Proces_produkcyjny DP_Proces_produkcyjny { get; set; }
    }
}
