//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Po_wydr_proc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DP_Po_wydr_proc()
        {
            this.DP_Po_material_wydruk = new HashSet<DP_Po_material_wydruk>();
            this.DP_Maszyna = new HashSet<DP_Maszyna>();
        }
    
        public int Id_po_wydr_proces { get; set; }
        public int Id_wydruk { get; set; }
        public int Id_proces_technologiczny { get; set; }
        public int Czas_zamierzony { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_Po_material_wydruk> DP_Po_material_wydruk { get; set; }
        public virtual DP_Proces_technologiczny DP_Proces_technologiczny { get; set; }
        public virtual DP_Wydruk DP_Wydruk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_Maszyna> DP_Maszyna { get; set; }
    }
}
