//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Serwis_zewnetrzny
    {
        public int Id_serwis_zewnetrzny { get; set; }
        public Nullable<int> Id_firma_serwisowa { get; set; }
        public Nullable<int> Id_maszyny { get; set; }
        public Nullable<int> Id_usluga_serwisu_zewnetrznego { get; set; }
        public decimal Koszt { get; set; }
        public System.DateTime Data_rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_zakonczenia { get; set; }
        public string Uwagi { get; set; }
    
        public virtual DP_Firma_serwisowa DP_Firma_serwisowa { get; set; }
        public virtual DP_Maszyna DP_Maszyna { get; set; }
        public virtual DP_Usluga_serwisu_zewnetrznego DP_Usluga_serwisu_zewnetrznego { get; set; }
    }
}
