//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Serwis_wewnetrzny_obsluga
    {
        public int Id_serwis_wewnetrzny_obsluga { get; set; }
        public Nullable<int> Id_maszyny { get; set; }
        public Nullable<int> Id_pracownik { get; set; }
        public Nullable<int> Id_czynnosc_w_ramach_obslugi_serw_wew { get; set; }
        public System.DateTime Data_rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_zakonczenia { get; set; }
    
        public virtual DP_Czynnosc_w_ramach_obslugi_serw_wew DP_Czynnosc_w_ramach_obslugi_serw_wew { get; set; }
        public virtual DP_Maszyna DP_Maszyna { get; set; }
        public virtual DZ_Pracownik DZ_Pracownik { get; set; }
    }
}
