//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Wydruk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DP_Wydruk()
        {
            this.DP_Po_wydr_proc = new HashSet<DP_Po_wydr_proc>();
        }
    
        public int Id_wydruk { get; set; }
        public string Wypelnienie { get; set; }
        public Nullable<int> Estymowany_czas { get; set; }
        public string Estymowana_masa { get; set; }
        public Nullable<int> Id_pliku { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_Po_wydr_proc> DP_Po_wydr_proc { get; set; }
        public virtual DZ_Plik DZ_Plik { get; set; }
    }
}
