//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DZ_Rodzaj_nieobecnosci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DZ_Rodzaj_nieobecnosci()
        {
            this.DZ_Nieobecnosc = new HashSet<DZ_Nieobecnosc>();
        }
    
        public int Id_rodzaj_nieobecnosci { get; set; }
        public string Rodzaj { get; set; }
        public double Procent_pensji { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DZ_Nieobecnosc> DZ_Nieobecnosc { get; set; }
    }
}
