//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DZ_Szczegoly_zatrudnienia
    {
        public int Id_szczegoly_zatrudnienia { get; set; }
        public Nullable<int> Id_zatrudnienia { get; set; }
        public System.DateTime data_zmiany_wynagrodzenia { get; set; }
        public double podstawa_wynagrodzenia { get; set; }
    
        public virtual DZ_Zatrudnienie DZ_Zatrudnienie { get; set; }
    }
}
