//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DZ_Szczegoly_zam_maszyn
    {
        public int Id_szczegoly_zam_maszyn { get; set; }
        public int Id_zamowienia_zewn { get; set; }
        public int Id_maszyny { get; set; }
        public double Koszt_jednostkowy_oferta { get; set; }
        public int Ilosc { get; set; }
    
        public virtual DP_Maszyna DP_Maszyna { get; set; }
        public virtual DZ_Zamowienie_zewn DZ_Zamowienie_zewn { get; set; }
    }
}
