//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DZ_Zatrudnienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DZ_Zatrudnienie()
        {
            this.DZ_Szczegoly_zatrudnienia = new HashSet<DZ_Szczegoly_zatrudnienia>();
        }
    
        public int Id_zatrudnienia { get; set; }
        public Nullable<int> Id_pracownika { get; set; }
        public Nullable<int> Id_stanowiska { get; set; }
        public Nullable<int> Id_dzialu { get; set; }
        public Nullable<int> Id_etatu { get; set; }
        public Nullable<int> Id_rodzaj_umowy { get; set; }
        public System.DateTime Data_zatrudnienia { get; set; }
        public System.DateTime Data_zwolnienia { get; set; }
    
        public virtual DZ_Dzial DZ_Dzial { get; set; }
        public virtual DZ_Etat DZ_Etat { get; set; }
        public virtual DZ_Pracownik DZ_Pracownik { get; set; }
        public virtual DZ_Rodzaj_umowy DZ_Rodzaj_umowy { get; set; }
        public virtual DZ_Stanowisko DZ_Stanowisko { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DZ_Szczegoly_zatrudnienia> DZ_Szczegoly_zatrudnienia { get; set; }
    }
}
