//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM_Wydanie_materialu_dla_produkcji
    {
        public int Identyfikator_wydania_materialu { get; set; }
        public int Numer_zamówienia { get; set; }
        public string C_Nazwisko_pracownika_pobierajacego { get; set; }
        public string C_Nazwisko_pracownika_wydajacego { get; set; }
        public System.DateTime C_Data_i_godzina { get; set; }
    }
}
