//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM_Narzedzie
    {
        public int Numer_narzedzia { get; set; }
        public string Nazwa { get; set; }
        public string Rodzaj_narzedzia { get; set; }
        public string Numer_seryjny { get; set; }
        public Nullable<System.DateTime> Data_zuzycia { get; set; }
    }
}
