//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM_Parametr_narzedzia
    {
        public string Nazwa_narzedzia { get; set; }
        public string Wlasciwosc { get; set; }
        public string Wartosc { get; set; }
    }
}
