//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM_Wydanie_produktu
    {
        public int Identyfikator_wydania_produktu { get; set; }
        public int Numer_zamowienia { get; set; }
        public string C_Nazwisko_pracownika_wydajacego { get; set; }
        public Nullable<System.DateTime> Data_i_godzina { get; set; }
        public string Uwagi { get; set; }
    }
}
