//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM_Sklad_dostawy_narzedzi
    {
        public int Identyfikator_dostawy { get; set; }
        public string Nazwa_dostawcy { get; set; }
        public string Nazwa_narzedzia { get; set; }
        public int Numer_zamowienia { get; set; }
        public int Ilosc { get; set; }
        public int C_Cena_jednostkowa_narzedzia { get; set; }
    }
}
