//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM_Wydanie_czesci_dla_produkcji
    {
        public int Identyfikator_wydania_materialu { get; set; }
        public string Nazwisko_pracownika_pobierajacego { get; set; }
        public string Nazwisko_pracownika_wydajacego { get; set; }
        public System.DateTime Data_i_godzina_wydania { get; set; }
        public string Uwagi { get; set; }
    }
}
