//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM_Magazyn_gotowych_produktow
    {
        public int Identyfikator_magazynu { get; set; }
        public int Numer_zamowienia { get; set; }
        public System.DateTime Data_i_godzina_przyjecia { get; set; }
        public string Uwagi { get; set; }
    }
}
