//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_Proces_Techno1
    {
        public int Identyfikator_procesu_technologicznego { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Liczba_czynnosci_dodatkowych { get; set; }
        public Nullable<int> Liczba_wydrukow { get; set; }
        public Nullable<int> Sumaryczny_czas_wydruku { get; set; }
    }
}
