//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_Obsluga
    {
        public int Identyfikator_obslugi { get; set; }
        public string Nazwa_obslugi { get; set; }
        public string Rodzaj_maszyny { get; set; }
        public int Czas_miedzy_obslugami { get; set; }
    }
}
