//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_prod_czynnosc_dodatkowa
    {
        public int Identyfikator_czynnosci_dodatkowej { get; set; }
        public int Identyfikator_procesu_produkcyjnego { get; set; }
        public string Nazwa_czynnosci { get; set; }
        public Nullable<int> Czas_pracy { get; set; }
    }
}
