//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_Koszt_materialu_ofertowy
    {
        public int Id_proces_technologiczny { get; set; }
        public int Id_po_wydr_proces { get; set; }
        public int Id_po_proc_czynnosci { get; set; }
        public string Nazwa { get; set; }
        public string Rodzaj_materialu { get; set; }
        public int Material_wydruk { get; set; }
        public int Material_dodatkowe { get; set; }
        public double Ilosc_wydruk { get; set; }
        public int Ilosc_dodatkowe { get; set; }
        public Nullable<double> Koszt_m_wydruk { get; set; }
        public Nullable<int> Koszt_m_dodatkowe { get; set; }
    }
}
