//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_Koszt_pracownika_powykonawczy
    {
        public int Id_proces_produkcyjny { get; set; }
        public int Id_prod_czynnosci_dodatkowe { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public int Id_pracownika { get; set; }
        public int Czas_pracy { get; set; }
        public double Koszt_pracownika { get; set; }
    }
}
