//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_Material_Proces
    {
        public int Id_po_proc_czynnosci { get; set; }
        public int Id_materialu { get; set; }
        public int Ilosc { get; set; }
        public string Nazwa { get; set; }
        public string Rodzaj_materialu { get; set; }
    }
}
