//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_Wydruk_Proces1
    {
        public int Id_po_wydr_proces { get; set; }
        public int Id_wydruk { get; set; }
        public string Wypelnienie { get; set; }
        public string Estymowana_masa { get; set; }
        public string Nazwa_elementu { get; set; }
        public int Czas_zamierzony { get; set; }
    }
}
