//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_WydrukProces
    {
        public int Numer_wydruku { get; set; }
        public string Nazwa_elementu { get; set; }
        public string Wypełnienie { get; set; }
        public string masa_w_g { get; set; }
        public string nr_seryjny_drukarki { get; set; }
        public string rodzaj_maszyny { get; set; }
        public string rodzaj_materialu { get; set; }
        public double Material_dodatkowy_w_g { get; set; }
        public string nazwa_procesu { get; set; }
    }
}
