//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_Maszyny
    {
        public int Numer_maszyny { get; set; }
        public string Rodzaj_maszyny { get; set; }
        public string Nazwa_modelu { get; set; }
        public string Numer_seryjny { get; set; }
        public System.DateTime Data_wprowadzenia_maszyny { get; set; }
        public decimal C_Koszt_1_roboczo_godziny { get; set; }
    }
}
