//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_Czynnosc_w_ramach_obslugi_serw_wew
    {
        public int Identyfikator { get; set; }
        public string Nazwa_obslugi { get; set; }
        public string Nazwa_czynnosci { get; set; }
    }
}
