//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_CzynnoscProces
    {
        public int ID_CZYNNOSCI { get; set; }
        public string NAZWA_CZYNNOSCI { get; set; }
        public string NARZEDZIE { get; set; }
        public string MASZYNA { get; set; }
        public string MATERIAL { get; set; }
        public int ILOSC_MATERIALU { get; set; }
        public string PRACOWNIK { get; set; }
        public string Nazwa { get; set; }
    }
}
