//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_Koszt_maszyn_wydruk_ofertowy
    {
        public int Id_proces_technologiczny { get; set; }
        public int Id_maszyny { get; set; }
        public int Czas_zamierzony { get; set; }
        public decimal Koszt_1rh { get; set; }
        public Nullable<decimal> Koszt_maszyn_wydruk_przed { get; set; }
    }
}
