//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_MaszynaWydruk_Proces
    {
        public int Id_po_wydr_proces { get; set; }
        public int Id_maszyny { get; set; }
        public string Nr_seryjny { get; set; }
        public string RODZAJ { get; set; }
    }
}
