//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_K_ofertowy
    {
        public int Id_proces_technologiczny { get; set; }
        public Nullable<decimal> Koszt_maszyn1_ofertowy { get; set; }
        public Nullable<decimal> Koszt_maszyn2_ofertowy { get; set; }
        public Nullable<int> Koszt_materialu1_ofertowy { get; set; }
        public Nullable<double> Koszt_materialu2_ofertowy { get; set; }
        public Nullable<double> Koszt_pracownik_ofertowy { get; set; }
    }
}
