//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDP_Serwis_zewnetrzny
    {
        public int Id_serwisu_zewnetrznego { get; set; }
        public string Nazwa_firmy_serwisowej { get; set; }
        public string Numer_seryjny_maszyny { get; set; }
        public string Nazwa_usługi { get; set; }
        public decimal Koszt { get; set; }
        public System.DateTime Data_rozpoczecia_serwisu { get; set; }
        public Nullable<System.DateTime> Data_zakonczenia_serwisu { get; set; }
        public string Uwagi { get; set; }
    }
}
