//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Oferta_dla_klienta
    {
        public int Id_zamowienia { get; set; }
        public string Status_zam { get; set; }
        public string Nip { get; set; }
        public string Nazwa_firmy { get; set; }
        public int Ilosc_sztuk { get; set; }
    }
}
