//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Zamowienie_zewn
    {
        public int Numer_zamowienia { get; set; }
        public string Pracownik_składający_zamówienie { get; set; }
        public System.DateTime Data_zamowienia { get; set; }
    }
}
