//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Wplyw
    {
        public Nullable<int> Numer_faktury { get; set; }
        public string Status_zamówienia { get; set; }
        public string NIP { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public string Status_wpływu { get; set; }
    }
}
