//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Nieobecnosc
    {
        public int Identyfikator_nieobecnoœci { get; set; }
        public string Nazwisko_pracownika { get; set; }
        public string Rodzaj_nieobecnosci { get; set; }
        public System.DateTime Data_rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_zakonczenia { get; set; }
    }
}
