//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Zatrudnienie
    {
        public int Identyfikator_zatrudnienia { get; set; }
        public int Numer_pracownika { get; set; }
        public int Identyfikator_stanowiska { get; set; }
        public int Identyfikator_dzialu { get; set; }
        public int C_Identyfikator_etatu { get; set; }
        public int Identyfikator_umowy { get; set; }
        public System.DateTime Data_zatrudnienia { get; set; }
        public System.DateTime C_Data_zwolnienia { get; set; }
    }
}
