//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Zatrudnienie
    {
        public int Identyfikator_zatrudnienia { get; set; }
        public string Nazwisko { get; set; }
        public string Stanowisko { get; set; }
        public string Dział { get; set; }
        public double Etat { get; set; }
        public string Rodzaj_umowy { get; set; }
        public System.DateTime Data_zatrudnienia { get; set; }
        public System.DateTime Data_zwolnienia { get; set; }
    }
}
