//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Klient
    {
        public int Numer_klienta { get; set; }
        public string Nazwa_firmy { get; set; }
        public string NIP { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public string Adres { get; set; }
        public string Miasto { get; set; }
        public string Kod_pocztowy { get; set; }
        public string E_mail { get; set; }
        public string telefon { get; set; }
        public string Numer_rachunku { get; set; }
    }
}
