//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Szczegoly_zatrudnienia
    {
        public int Identyfikator_szczegolow_zatrudnienia { get; set; }
        public string Nazwisko_pracownika { get; set; }
        public System.DateTime Data_zmiany_wynagrodzenia { get; set; }
        public double Podstawa_wynagrodzenia { get; set; }
    }
}
