//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Oplaty_stale
    {
        public int Numer_rachunku { get; set; }
        public string Rodzaj_rachunku { get; set; }
        public double Koszt { get; set; }
        public System.DateTime Data_zapłaty { get; set; }
    }
}
