//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Po_szczegoly_zam_produkt
    {
        public int Identyfikator_szczegolow_produktu { get; set; }
        public string Numer_produktu { get; set; }
    }
}
