//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Szczegoly_zam_maszyn
    {
        public int Identyfikator_szczegolow_zamowienia_maszyn { get; set; }
        public int Numer_zamówienia { get; set; }
        public string Numer_seryjny { get; set; }
        public double Koszt_jednostkowy_oferty { get; set; }
        public int Ilość { get; set; }
    }
}
