//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Szczegoly_zamowienia_klienta
    {
        public int Identyfikator_szczegolow_zamowienia_klienta { get; set; }
        public int Numer_zamowienia { get; set; }
        public string Nazwa_pliku { get; set; }
        public int Iloœæ_sztuk { get; set; }
        public string Nazwa_materia_u { get; set; }
    }
}
