//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDZ_Szczegoly_zam_narzedzi
    {
        public int Identyfikator_szczegolow_zamowienia_narzedzi { get; set; }
        public int Numer_zamowienia { get; set; }
        public string Nazwa_narzêdzia { get; set; }
        public double Koszt_jednostkowy_oferty { get; set; }
        public string Nazwa__w_aœciwoœci { get; set; }
        public int Iloœæ { get; set; }
    }
}
