//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Narzedzie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_Narzedzie()
        {
            this.DM_Parametry_narzedzia = new HashSet<DM_Parametry_narzedzia>();
            this.DM_Sklad_dostawy_narzedzi = new HashSet<DM_Sklad_dostawy_narzedzi>();
            this.DM_Szczegoly_wypozyczenia_narzedzia = new HashSet<DM_Szczegoly_wypozyczenia_narzedzia>();
            this.DM_Zuzyte_narzedzia = new HashSet<DM_Zuzyte_narzedzia>();
            this.DZ_Szczegoly_zam_narzedzi = new HashSet<DZ_Szczegoly_zam_narzedzi>();
        }
    
        public int Id_narzedzia { get; set; }
        public string nazwa { get; set; }
        public int Id_rodzaj_narzedzia { get; set; }
        public int ilosc_poczatkowa { get; set; }
    
        public virtual DM_Rodzaj_narzedzia DM_Rodzaj_narzedzia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Parametry_narzedzia> DM_Parametry_narzedzia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Sklad_dostawy_narzedzi> DM_Sklad_dostawy_narzedzi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Szczegoly_wypozyczenia_narzedzia> DM_Szczegoly_wypozyczenia_narzedzia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Zuzyte_narzedzia> DM_Zuzyte_narzedzia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DZ_Szczegoly_zam_narzedzi> DZ_Szczegoly_zam_narzedzi { get; set; }
    }
}
