//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Szczegoly_wydania_materialu
    {
        public Nullable<int> Id_wydanie_materialu_dla_produkcji { get; set; }
        public int Id_materialu { get; set; }
        public int ilosc { get; set; }
    
        public virtual DM_Material DM_Material { get; set; }
        public virtual DM_Wydanie_materialu_dla_produkcji DM_Wydanie_materialu_dla_produkcji { get; set; }
    }
}
