//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Wydanie_materialu_dla_produkcji
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_Wydanie_materialu_dla_produkcji()
        {
            this.DM_Szczegoly_wydania_materialu = new HashSet<DM_Szczegoly_wydania_materialu>();
        }
    
        public int Id_wydanie_materialu_dla_produkcji { get; set; }
        public int Id_zamowienia { get; set; }
        public int Id_pracownik_pobierajacy { get; set; }
        public int Id_pracownik_wydajacy { get; set; }
        public System.DateTime data_i_godzina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Szczegoly_wydania_materialu> DM_Szczegoly_wydania_materialu { get; set; }
        public virtual DZ_Pracownik DZ_Pracownik { get; set; }
        public virtual DZ_Pracownik DZ_Pracownik1 { get; set; }
        public virtual DZ_Zamowienie_klienta DZ_Zamowienie_klienta { get; set; }
    }
}
