//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Rodzaj_czynnosci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DP_Rodzaj_czynnosci()
        {
            this.DP_Po_proc_czynnosci = new HashSet<DP_Po_proc_czynnosci>();
            this.DP_prod_czynnosci_dodatkowe = new HashSet<DP_prod_czynnosci_dodatkowe>();
        }
    
        public int Id_rodzaj_czynnosci { get; set; }
        public string nazwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_Po_proc_czynnosci> DP_Po_proc_czynnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_prod_czynnosci_dodatkowe> DP_prod_czynnosci_dodatkowe { get; set; }
    }
}
